/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.19 from the
 * contents of SHA.xs. Do not edit this file, edit SHA.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "SHA.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifdef SvPVbyte
	#if PERL_REVISION == 5 && PERL_VERSION < 8
		#undef SvPVbyte
		#define SvPVbyte(sv, lp) \
			(sv_utf8_downgrade((sv), 0), SvPV((sv), (lp)))
	#endif
#else
	#define SvPVbyte SvPV
#endif

#ifndef dTHX
	#define pTHX_
	#define aTHX_
#endif

#ifndef PerlIO
	#define PerlIO				FILE
	#define PerlIO_read(f, buf, count)	fread(buf, 1, count, f)
#endif

#ifndef sv_derived_from
	#include "src/sdf.c"
#endif

#ifndef Newx
	#define Newx(ptr, num, type)	New(0, ptr, num, type)
	#define Newxz(ptr, num, type)	Newz(0, ptr, num, type)
#endif

#include "src/sha.c"

static const int ix2alg[] =
	{1,1,1,224,224,224,256,256,256,384,384,384,512,512,512,
	512224,512224,512224,512256,512256,512256};

#ifndef INT2PTR
#define INT2PTR(p, i) (p) (i)
#endif

#define MAX_WRITE_SIZE 16384
#define IO_BUFFER_SIZE 4096

static SHA *getSHA(pTHX_ SV *self)
{
	if (!sv_isobject(self) || !sv_derived_from(self, "Digest::SHA"))
		return(NULL);
	return INT2PTR(SHA *, SvIV(SvRV(self)));
}

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 69 "SHA.c"

XS(XS_Digest__SHA_shainit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_shainit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::shainit", "s, alg");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SHA *	s = getSHA(aTHX_ ST(0));
	int	alg = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = shainit(s, alg);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_sharewind); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_sharewind)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::sharewind", "s");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SHA *	s = getSHA(aTHX_ ST(0));

	sharewind(s);
    }
    XSRETURN_EMPTY;
}


XS(XS_Digest__SHA_shawrite); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_shawrite)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::shawrite", "bitstr, bitcnt, s");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	unsigned char *	bitstr = (unsigned char *)SvPV_nolen(ST(0));
	unsigned long	bitcnt = (unsigned long)SvUV(ST(1));
	SHA *	s = getSHA(aTHX_ ST(2));
	unsigned long	RETVAL;
	dXSTARG;

	RETVAL = shawrite(bitstr, bitcnt, s);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_newSHA); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_newSHA)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::newSHA", "classname, alg");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	classname = (char *)SvPV_nolen(ST(0));
	int	alg = (int)SvIV(ST(1));
#line 79 "SHA.xs"
	SHA *state;
#line 156 "SHA.c"
	SV *	RETVAL;
#line 81 "SHA.xs"
	Newxz(state, 1, SHA);
	if (!shainit(state, alg)) {
		Safefree(state);
		XSRETURN_UNDEF;
	}
	RETVAL = newSV(0);
	sv_setref_pv(RETVAL, classname, (void *) state);
	SvREADONLY_on(SvRV(RETVAL));
#line 167 "SHA.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_clone); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_clone)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::clone", "self");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	self = ST(0);
#line 96 "SHA.xs"
	SHA *state;
	SHA *clone;
#line 191 "SHA.c"
	SV *	RETVAL;
#line 99 "SHA.xs"
	if ((state = getSHA(aTHX_ self)) == NULL)
		XSRETURN_UNDEF;
	Newx(clone, 1, SHA);
	RETVAL = newSV(0);
	sv_setref_pv(RETVAL, sv_reftype(SvRV(self), 1), (void *) clone);
	SvREADONLY_on(SvRV(RETVAL));
	Copy(state, clone, 1, SHA);
#line 201 "SHA.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::DESTROY", "s");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SHA *	s = getSHA(aTHX_ ST(0));
#line 113 "SHA.xs"
	Safefree(s);
#line 224 "SHA.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Digest__SHA_sha1); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_sha1)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 140 "SHA.xs"
	int i;
	UCHR *data;
	STRLEN len;
	SHA sha;
	char *result;
#line 247 "SHA.c"
	SV *	RETVAL;
#line 146 "SHA.xs"
	if (!shainit(&sha, ix2alg[ix]))
		XSRETURN_UNDEF;
	for (i = 0; i < items; i++) {
		data = (UCHR *) (SvPVbyte(ST(i), len));
		while (len > MAX_WRITE_SIZE) {
			shawrite(data, MAX_WRITE_SIZE << 3, &sha);
			data += MAX_WRITE_SIZE;
			len  -= MAX_WRITE_SIZE;
		}
		shawrite(data, (ULNG) len << 3, &sha);
	}
	shafinish(&sha);
	len = 0;
	if (ix % 3 == 0) {
		result = (char *) shadigest(&sha);
		len = sha.digestlen;
	}
	else if (ix % 3 == 1)
		result = shahex(&sha);
	else
		result = shabase64(&sha);
	RETVAL = newSVpv(result, len);
#line 272 "SHA.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_hmac_sha1); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_hmac_sha1)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 196 "SHA.xs"
	int i;
	UCHR *key = (UCHR *) "";
	UCHR *data;
	STRLEN len = 0;
	HMAC hmac;
	char *result;
#line 298 "SHA.c"
	SV *	RETVAL;
#line 203 "SHA.xs"
	if (items > 0) {
		key = (UCHR *) (SvPVbyte(ST(items-1), len));
	}
	if (hmacinit(&hmac, ix2alg[ix], key, (UINT) len) == NULL)
		XSRETURN_UNDEF;
	for (i = 0; i < items - 1; i++) {
		data = (UCHR *) (SvPVbyte(ST(i), len));
		while (len > MAX_WRITE_SIZE) {
			hmacwrite(data, MAX_WRITE_SIZE << 3, &hmac);
			data += MAX_WRITE_SIZE;
			len  -= MAX_WRITE_SIZE;
		}
		hmacwrite(data, (ULNG) len << 3, &hmac);
	}
	hmacfinish(&hmac);
	len = 0;
	if (ix % 3 == 0) {
		result = (char *) hmacdigest(&hmac);
		len = hmac.digestlen;
	}
	else if (ix % 3 == 1)
		result = hmachex(&hmac);
	else
		result = hmacbase64(&hmac);
	RETVAL = newSVpv(result, len);
#line 326 "SHA.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_hashsize); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_hashsize)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", GvNAME(CvGV(cv)), "self");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	self = ST(0);
#line 238 "SHA.xs"
	SHA *state;
#line 350 "SHA.c"
	int	RETVAL;
	dXSTARG;
#line 240 "SHA.xs"
	if ((state = getSHA(aTHX_ self)) == NULL)
		XSRETURN_UNDEF;
	RETVAL = ix ? state->alg : (int) (state->digestlen << 3);
#line 357 "SHA.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::add", "self, ...");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	self = ST(0);
#line 250 "SHA.xs"
	int i;
	UCHR *data;
	STRLEN len;
	SHA *state;
#line 384 "SHA.c"
#line 255 "SHA.xs"
	if ((state = getSHA(aTHX_ self)) == NULL)
		XSRETURN_UNDEF;
	for (i = 1; i < items; i++) {
		data = (UCHR *) (SvPVbyte(ST(i), len));
		while (len > MAX_WRITE_SIZE) {
			shawrite(data, MAX_WRITE_SIZE << 3, state);
			data += MAX_WRITE_SIZE;
			len  -= MAX_WRITE_SIZE;
		}
		shawrite(data, (ULNG) len << 3, state);
	}
	XSRETURN(1);
#line 398 "SHA.c"
	PUTBACK;
	return;
    }
}


XS(XS_Digest__SHA_digest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA_digest)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", GvNAME(CvGV(cv)), "self");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	self = ST(0);
#line 276 "SHA.xs"
	STRLEN len;
	SHA *state;
	char *result;
#line 423 "SHA.c"
	SV *	RETVAL;
#line 280 "SHA.xs"
	if ((state = getSHA(aTHX_ self)) == NULL)
		XSRETURN_UNDEF;
	shafinish(state);
	len = 0;
	if (ix == 0) {
		result = (char *) shadigest(state);
		len = state->digestlen;
	}
	else if (ix == 1)
		result = shahex(state);
	else
		result = shabase64(state);
	RETVAL = newSVpv(result, len);
	sharewind(state);
#line 440 "SHA.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA__getstate); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA__getstate)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::_getstate", "self");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	self = ST(0);
#line 301 "SHA.xs"
	SHA *state;
	UCHR buf[256];
	UCHR *ptr = buf;
#line 465 "SHA.c"
	SV *	RETVAL;
#line 305 "SHA.xs"
	if ((state = getSHA(aTHX_ self)) == NULL)
		XSRETURN_UNDEF;
	Copy(digcpy(state), ptr, state->alg <= SHA256 ? 32 : 64, UCHR);
	ptr += state->alg <= SHA256 ? 32 : 64;
	Copy(state->block, ptr, state->alg <= SHA256 ? 64 : 128, UCHR);
	ptr += state->alg <= SHA256 ? 64 : 128;
	ptr = w32mem(ptr, state->blockcnt);
	ptr = w32mem(ptr, state->lenhh);
	ptr = w32mem(ptr, state->lenhl);
	ptr = w32mem(ptr, state->lenlh);
	ptr = w32mem(ptr, state->lenll);
	RETVAL = newSVpv((char *) buf, (STRLEN) (ptr - buf));
#line 480 "SHA.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Digest__SHA__putstate); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA__putstate)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::_putstate", "self, packed_state");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	self = ST(0);
	SV *	packed_state = ST(1);
#line 325 "SHA.xs"
	UINT bc;
	STRLEN len;
	SHA *state;
	UCHR *data;
#line 509 "SHA.c"
#line 330 "SHA.xs"
	if ((state = getSHA(aTHX_ self)) == NULL)
		XSRETURN_UNDEF;
	data = (UCHR *) SvPV(packed_state, len);
	if (len != (state->alg <= SHA256 ? 116U : 212U))
		XSRETURN_UNDEF;
	data = statecpy(state, data);
	Copy(data, state->block, state->blocksize >> 3, UCHR);
	data += (state->blocksize >> 3);
	bc = memw32(data), data += 4;
	if (bc >= (state->alg <= SHA256 ? 512U : 1024U))
		XSRETURN_UNDEF;
	state->blockcnt = bc;
	state->lenhh = memw32(data), data += 4;
	state->lenhl = memw32(data), data += 4;
	state->lenlh = memw32(data), data += 4;
	state->lenll = memw32(data);
	XSRETURN(1);
#line 528 "SHA.c"
	PUTBACK;
	return;
    }
}


XS(XS_Digest__SHA__addfilebin); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA__addfilebin)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::_addfilebin", "self, f");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	self = ST(0);
	PerlIO *	f = IoIFP(sv_2io(ST(1)));
#line 353 "SHA.xs"
	SHA *state;
	int n;
	UCHR in[IO_BUFFER_SIZE];
#line 555 "SHA.c"
#line 357 "SHA.xs"
	if (!f || (state = getSHA(aTHX_ self)) == NULL)
		XSRETURN_UNDEF;
	while ((n = (int) PerlIO_read(f, in, sizeof(in))) > 0)
		shawrite(in, (ULNG) n << 3, state);
	XSRETURN(1);
#line 562 "SHA.c"
	PUTBACK;
	return;
    }
}


XS(XS_Digest__SHA__addfileuniv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Digest__SHA__addfileuniv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Digest::SHA::_addfileuniv", "self, f");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	self = ST(0);
	PerlIO *	f = IoIFP(sv_2io(ST(1)));
#line 368 "SHA.xs"
	UCHR c;
	int n;
	int cr = 0;
	UCHR *src, *dst;
	UCHR in[IO_BUFFER_SIZE+1];
	SHA *state;
#line 592 "SHA.c"
#line 375 "SHA.xs"
	if (!f || (state = getSHA(aTHX_ self)) == NULL)
		XSRETURN_UNDEF;
	while ((n = (int) PerlIO_read(f, in+1, IO_BUFFER_SIZE)) > 0) {
		for (dst = in, src = in + 1; n; n--) {
			c = *src++;
			if (!cr) {
				if (c == '\015')
					cr = 1;
				else
					*dst++ = c;
			}
			else {
				if (c == '\015')
					*dst++ = '\012';
				else if (c == '\012') {
					*dst++ = '\012';
					cr = 0;
				}
				else {
					*dst++ = '\012';
					*dst++ = c;
					cr = 0;
				}
			}
		}
		shawrite(in, (ULNG) (dst - in) << 3, state);
	}
	if (cr) {
		in[0] = '\012';
		shawrite(in, 1UL << 3, state);
	}
	XSRETURN(1);
#line 626 "SHA.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Digest__SHA); /* prototype to pass -Wmissing-prototypes */
XS(boot_Digest__SHA)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

    {
        CV * cv ;

        newXSproto("Digest::SHA::shainit", XS_Digest__SHA_shainit, file, "$$");
        newXSproto("Digest::SHA::sharewind", XS_Digest__SHA_sharewind, file, "$");
        newXSproto("Digest::SHA::shawrite", XS_Digest__SHA_shawrite, file, "$$$");
        newXSproto("Digest::SHA::newSHA", XS_Digest__SHA_newSHA, file, "$$");
        newXSproto("Digest::SHA::clone", XS_Digest__SHA_clone, file, "$");
        newXSproto("Digest::SHA::DESTROY", XS_Digest__SHA_DESTROY, file, "$");
        cv = newXS("Digest::SHA::sha512_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 13 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha512_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 14 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha224", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 3 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha256_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 7 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha384_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 10 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha512", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 12 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha512224", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 15 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha1_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 1 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha256", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 6 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha384_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 11 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha1_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 2 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha224_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 4 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha512224_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 16 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha512256_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 20 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha384", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 9 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha256_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 8 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha224_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 5 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha1", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 0 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha512256", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 18 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha512224_base64", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 17 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::sha512256_hex", XS_Digest__SHA_sha1, file);
        XSANY.any_i32 = 19 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha1_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 2 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha1", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 0 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha1_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 1 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha224", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 3 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512224_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 17 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha384_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 10 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 14 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512224_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 16 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha256_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 7 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512224", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 15 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 12 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512256", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 18 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha256", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 6 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512256_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 19 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha224_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 4 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha384", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 9 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha256_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 8 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha384_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 11 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha224_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 5 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512256_base64", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 20 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::hmac_sha512_hex", XS_Digest__SHA_hmac_sha1, file);
        XSANY.any_i32 = 13 ;
        sv_setpv((SV*)cv, ";@") ;
        cv = newXS("Digest::SHA::algorithm", XS_Digest__SHA_hashsize, file);
        XSANY.any_i32 = 1 ;
        sv_setpv((SV*)cv, "$") ;
        cv = newXS("Digest::SHA::hashsize", XS_Digest__SHA_hashsize, file);
        XSANY.any_i32 = 0 ;
        sv_setpv((SV*)cv, "$") ;
        newXSproto("Digest::SHA::add", XS_Digest__SHA_add, file, "$;@");
        cv = newXS("Digest::SHA::digest", XS_Digest__SHA_digest, file);
        XSANY.any_i32 = 0 ;
        sv_setpv((SV*)cv, "$") ;
        cv = newXS("Digest::SHA::b64digest", XS_Digest__SHA_digest, file);
        XSANY.any_i32 = 2 ;
        sv_setpv((SV*)cv, "$") ;
        cv = newXS("Digest::SHA::hexdigest", XS_Digest__SHA_digest, file);
        XSANY.any_i32 = 1 ;
        sv_setpv((SV*)cv, "$") ;
        newXSproto("Digest::SHA::_getstate", XS_Digest__SHA__getstate, file, "$");
        newXSproto("Digest::SHA::_putstate", XS_Digest__SHA__putstate, file, "$$");
        newXSproto("Digest::SHA::_addfilebin", XS_Digest__SHA__addfilebin, file, "$$");
        newXSproto("Digest::SHA::_addfileuniv", XS_Digest__SHA__addfileuniv, file, "$$");
    }
    XSRETURN_YES;
}

